# ─────────────────────────────────────────────────────────────────────────────
#  netlify.toml
#
#  This tells Netlify:
#    • “Publish” (i.e. serve) everything in the repository root (".")
#    • Look for serverless functions under netlify/functions
#    • Don’t run any build commands
# ─────────────────────────────────────────────────────────────────────────────

[build]
  # No build command (we are just serving static HTML/JS/CSS files).
  command = ""

  # “Publish directory = "."” means “just take the repo root and deploy it.”
  publish = "."

  # “Functions directory = netlify/functions” points Netlify at your Lambda code.
  functions = "netlify/functions"
